#!/bin/bash

STATEFILE="$XDG_RUNTIME_DIR/ewwii_calendar_popup_state"

if [[ -f $STATEFILE ]]; then
  last_state=$(cat $STATEFILE)
else
  last_state="closed"
fi

if [[ $last_state == "open" ]]; then
  ewwii close calendar_popup
  echo "closed" >$STATEFILE
else
  ewwii open calendar_popup
  echo "open" >$STATEFILE
fi
sleep 0.2
