#!/bin/bash
ws_num="$1"

print_status() {
  local ws_num=$1
  local ws_json
  ws_json=$(i3-msg -t get_workspaces)
  local ws
  ws=$(echo "$ws_json" | jq -r --arg ws "$ws_num" '.[] | select(.name == $ws)')
  if [ -z "$ws" ]; then
    echo "◯"
  else
    local focused
    focused=$(echo "$ws" | jq -r '.focused')
    local num_windows
    num_windows=$(echo "$ws" | jq -r '.num')
    if [ "$focused" = "true" ]; then
      echo "⬤"
    elif [ "$num_windows" -gt 0 ]; then
      echo "●"
    else
      echo "◯"
    fi
  fi
}

print_status "$ws_num"

i3-msg -t subscribe -m '[ "workspace" ]' | while read -r event; do
  print_status "$ws_num"
done
