# IMPORTANT NOTE
# This structure of this config file, should be kept the same and only the values should be customised.
# Only tweak the values, changing the key names or removing them may result in any unnecessary bugs or errors.

[appearance]
theme = "dark"
wallpaper = "/usr/share/backgrounds/theom/mountains.jpg"

[bar]
polybar_layout = "float"
use_eww = true

[widgets]
enable_widgets = true
show = [
    "~/.config/theom/twidgets/time.lua",
    "~/.config/theom/twidgets/uptime.lua"
]

[compositor]
compositing = true
compositing_mode = "performance" # performance mode is light and recommended and compatibility mode is heavy and prevents visual glitches. 
animations = "basic" # options: none, basic, fancy

[osd]
osd = false

[functions]
autoset_appconfs = true # Autoset the default configuration of apps in their config root
enable_nightlight = false # Enables nightlight filter to protect your eyes.