#!/bin/bash

STATEFILE=/tmp/eww_calendar_popup_state

if [[ -f $STATEFILE ]]; then
  last_state=$(cat $STATEFILE)
else
  last_state="closed"
fi

if [[ $last_state == "open" ]]; then
  eww close calendar_popup
  echo "closed" > $STATEFILE
else
  eww open calendar_popup
  echo "open" > $STATEFILE
fi
sleep 0.1