#!/bin/bash

theme=$1
echo $theme

if pgrep -x "xfsrtray" > /dev/null; then
    killall xfsrtray
else
    if [ "$theme" = "dark" ]; then
        xfsrtray --set-to-content-size --background-color "282c34" --margin-y 60 --margin-x=-40 --position "TR" --padding 5
    else
        xfsrtray --set-to-content-size --background-color "A88C5A" --margin-y 60 --margin-x=-40 --position "TR" --padding 5
    fi
fi
