#!/bin/bash

theme=$1
echo $theme

if pgrep -x "theom-systray" > /dev/null; then
    killall theom-systray
else
    if [ "$theme" = "dark" ]; then
        theom-systray --set-to-item-width --background-color "282c34" --margin-y 60 --margin-x=-40 --position "TR" --padding 5
    else
        theom-systray --set-to-item-width --background-color "A88C5A" --margin-y 60 --margin-x=-40 --position "TR" --padding 5
    fi
fi
