#!/bin/bash

if pgrep -x "theom-systray" > /dev/null; then
    killall theom-systray
else
    /home/byson94/Documents/Programming/Theom-packages/theom-systray/src/theom-systray --set-to-item-width --background-color "000000" --margin-y 60 --margin-x=-40 --position "TR" --padding 5
fi
