name: Code Syntax Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y shellcheck
      - run: find . -type f -name "*.sh" | xargs -r shellcheck

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y python3-pip
      - run: pip install flake8
      - run: flake8 .

  lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y luarocks
      - run: sudo luarocks install luacheck
      - run: luacheck . --config .github/workflows/luacheckrc

  scss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y sassc
      - run: find . -type f -name "*.scss" | while read f; do sassc "$f" /dev/null; done

  manpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y man-db
      - run: find . -name "*.1" | while read f; do man -l "$f" > /dev/null; done
